[package]
name = "pixel_sorter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
env_logger = "0.10"
log = "0.4"
show-image = "0.13.1"
rand = "0.8.5"
rayon = "1.7.0"

